// Code generated by MockGen. DO NOT EDIT.
// Source: type.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/soerjadi/monsterdex/internal/model"
)

// MockAccessTokenUsecase is a mock of Usecase interface.
type MockAccessTokenUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockAccessTokenUsecaseMockRecorder
}

// MockAccessTokenUsecaseMockRecorder is the mock recorder for MockAccessTokenUsecase.
type MockAccessTokenUsecaseMockRecorder struct {
	mock *MockAccessTokenUsecase
}

// NewMockAccessTokenUsecase creates a new mock instance.
func NewMockAccessTokenUsecase(ctrl *gomock.Controller) *MockAccessTokenUsecase {
	mock := &MockAccessTokenUsecase{ctrl: ctrl}
	mock.recorder = &MockAccessTokenUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccessTokenUsecase) EXPECT() *MockAccessTokenUsecaseMockRecorder {
	return m.recorder
}

// GetUserIDByToken mocks base method.
func (m *MockAccessTokenUsecase) GetUserIDByToken(ctx context.Context, token string) (model.AccessToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserIDByToken", ctx, token)
	ret0, _ := ret[0].(model.AccessToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserIDByToken indicates an expected call of GetUserIDByToken.
func (mr *MockAccessTokenUsecaseMockRecorder) GetUserIDByToken(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserIDByToken", reflect.TypeOf((*MockAccessTokenUsecase)(nil).GetUserIDByToken), ctx, token)
}
