// Code generated by MockGen. DO NOT EDIT.
// Source: type.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/soerjadi/monsterdex/internal/model"
)

// MockMonsterUsecase is a mock of Usecase interface.
type MockMonsterUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockMonsterUsecaseMockRecorder
}

// MockMonsterUsecaseMockRecorder is the mock recorder for MockMonsterUsecase.
type MockMonsterUsecaseMockRecorder struct {
	mock *MockMonsterUsecase
}

// NewMockMonsterUsecase creates a new mock instance.
func NewMockMonsterUsecase(ctrl *gomock.Controller) *MockMonsterUsecase {
	mock := &MockMonsterUsecase{ctrl: ctrl}
	mock.recorder = &MockMonsterUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMonsterUsecase) EXPECT() *MockMonsterUsecaseMockRecorder {
	return m.recorder
}

// CaptureMonster mocks base method.
func (m *MockMonsterUsecase) CaptureMonster(ctx context.Context, req model.CaptureMonsterReq) (model.CapturedMonster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CaptureMonster", ctx, req)
	ret0, _ := ret[0].(model.CapturedMonster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CaptureMonster indicates an expected call of CaptureMonster.
func (mr *MockMonsterUsecaseMockRecorder) CaptureMonster(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CaptureMonster", reflect.TypeOf((*MockMonsterUsecase)(nil).CaptureMonster), ctx, req)
}

// DeleteMonster mocks base method.
func (m *MockMonsterUsecase) DeleteMonster(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMonster", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMonster indicates an expected call of DeleteMonster.
func (mr *MockMonsterUsecaseMockRecorder) DeleteMonster(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMonster", reflect.TypeOf((*MockMonsterUsecase)(nil).DeleteMonster), ctx, id)
}

// GetDetailMonster mocks base method.
func (m *MockMonsterUsecase) GetDetailMonster(ctx context.Context, id, userID int64) (model.Monster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDetailMonster", ctx, id, userID)
	ret0, _ := ret[0].(model.Monster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDetailMonster indicates an expected call of GetDetailMonster.
func (mr *MockMonsterUsecaseMockRecorder) GetDetailMonster(ctx, id, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDetailMonster", reflect.TypeOf((*MockMonsterUsecase)(nil).GetDetailMonster), ctx, id, userID)
}

// GetListMonster mocks base method.
func (m *MockMonsterUsecase) GetListMonster(ctx context.Context, req model.MonsterListRequest, userID int64) ([]model.Monster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListMonster", ctx, req, userID)
	ret0, _ := ret[0].([]model.Monster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetListMonster indicates an expected call of GetListMonster.
func (mr *MockMonsterUsecaseMockRecorder) GetListMonster(ctx, req, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListMonster", reflect.TypeOf((*MockMonsterUsecase)(nil).GetListMonster), ctx, req, userID)
}

// InsertMonster mocks base method.
func (m *MockMonsterUsecase) InsertMonster(ctx context.Context, req model.MonsterRequest) (model.MonsterData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertMonster", ctx, req)
	ret0, _ := ret[0].(model.MonsterData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertMonster indicates an expected call of InsertMonster.
func (mr *MockMonsterUsecaseMockRecorder) InsertMonster(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertMonster", reflect.TypeOf((*MockMonsterUsecase)(nil).InsertMonster), ctx, req)
}

// UpdateMonster mocks base method.
func (m *MockMonsterUsecase) UpdateMonster(ctx context.Context, req model.MonsterRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMonster", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMonster indicates an expected call of UpdateMonster.
func (mr *MockMonsterUsecaseMockRecorder) UpdateMonster(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMonster", reflect.TypeOf((*MockMonsterUsecase)(nil).UpdateMonster), ctx, req)
}
